---

version: 2

steps: &steps
  steps:
    - checkout

    - restore_cache:
        keys:
          - dependencies-{{ checksum "Gemfile.lock" }}

    - run:
        name: Run CI checks
        command: bin/ci.sh

    - persist_to_workspace:
        root: ./coverage
        paths:
          - "**/.resultset.json"

    - save_cache:
        key: dependencies-{{ checksum "Gemfile.lock" }}
        paths:
          - .bundle

jobs:
  prior-to-prior-to-latest-readline-gcc:
    docker:
      - image: deividrodriguez/byebug:2.3.7-readline-gcc
    <<: *steps

  prior-to-prior-to-latest-libedit-gcc:
    docker:
      - image: deividrodriguez/byebug:2.3.7-libedit-gcc
    <<: *steps

  prior-to-prior-to-latest-readline-clang:
    docker:
      - image: deividrodriguez/byebug:2.3.7-readline-clang
    <<: *steps

  prior-to-prior-to-latest-libedit-clang:
    docker:
      - image: deividrodriguez/byebug:2.3.7-libedit-clang
    <<: *steps

  prior-to-latest-readline-gcc:
    docker:
      - image: deividrodriguez/byebug:2.4.4-readline-gcc
    <<: *steps

  prior-to-latest-libedit-gcc:
    docker:
      - image: deividrodriguez/byebug:2.4.4-libedit-gcc
    <<: *steps

  prior-to-latest-readline-clang:
    docker:
      - image: deividrodriguez/byebug:2.4.4-readline-clang
    <<: *steps

  prior-to-latest-libedit-clang:
    docker:
      - image: deividrodriguez/byebug:2.4.4-libedit-clang
    <<: *steps

  latest-readline-gcc:
    docker:
      - image: deividrodriguez/byebug:2.5.1-readline-gcc
    <<: *steps

  latest-libedit-gcc:
    docker:
      - image: deividrodriguez/byebug:2.5.1-libedit-gcc
    <<: *steps

  latest-readline-clang:
    docker:
      - image: deividrodriguez/byebug:2.5.1-readline-clang
    <<: *steps

  latest-libedit-clang:
    docker:
      - image: deividrodriguez/byebug:2.5.1-libedit-clang
    <<: *steps

  coverage:
    docker:
      - image: deividrodriguez/byebug:2.5.1-readline-clang

    steps:
      - checkout

      - attach_workspace:
          at: ./coverage

      - restore_cache:
          keys:
            - dependencies-{{ checksum "Gemfile.lock" }}

      - run:
          name: Install dependencies
          command: bin/bundle install --jobs 3 --retry 3 --path .bundle

      - save_cache:
          key: dependencies-{{ checksum "Gemfile.lock" }}
          paths:
            - .bundle

      - run:
          name: Upload coverage results to Code Climate
          command: bin/rake coverage:report

      - store_artifacts:
          path: coverage/index.html

workflows:
  version: 2

  test:
    jobs:
      - prior-to-prior-to-latest-readline-gcc
      - prior-to-prior-to-latest-libedit-gcc
      - prior-to-prior-to-latest-readline-clang
      - prior-to-prior-to-latest-libedit-clang

      - prior-to-latest-readline-gcc
      - prior-to-latest-libedit-gcc
      - prior-to-latest-readline-clang
      - prior-to-latest-libedit-clang

      - latest-readline-gcc
      - latest-libedit-gcc
      - latest-readline-clang
      - latest-libedit-clang

      - coverage:
          requires:
            - prior-to-prior-to-latest-readline-gcc
            - prior-to-prior-to-latest-libedit-gcc
            - prior-to-prior-to-latest-readline-clang
            - prior-to-prior-to-latest-libedit-clang

            - prior-to-latest-readline-gcc
            - prior-to-latest-libedit-gcc
            - prior-to-latest-readline-clang
            - prior-to-latest-libedit-clang

            - latest-readline-gcc
            - latest-libedit-gcc
            - latest-readline-clang
            - latest-libedit-clang
